# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: voice.forum::lang.channels.name

# Model Form Field configuration
form: ~/plugins/voice/forum/models/channel/fields.yaml

# Model Class name
modelClass: Voice\Forum\Models\Channel

# Default redirect location
defaultRedirect: voice/forum/channels

# Create page
create:
    title: voice.forum::lang.channels.create
    redirect: voice/forum/channels/update/:id
    redirectClose: voice/forum/channels

# Update page
update:
    title: voice.forum::lang.channels.update
    redirect: voice/forum/channels
    redirectClose: voice/forum/channels

# Preview page
preview:
    title: voice.forum::lang.channels.preview