# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Category

# Model Form Field configuration
form: $/wo/cao/models/category/fields.yaml

# Model Class name
modelClass: Wo\Cao\Models\Category

# Default redirect location
defaultRedirect: wo/cao/categories

# Create page
create:
    title: Create Category
    redirect: wo/cao/categories/update/:id
    redirectClose: wo/cao/categories

# Update page
update:
    title: Edit Category
    redirect: wo/cao/categories
    redirectClose: wo/cao/categories

# Preview page
preview:
    title: Preview Category